all-1: build run
build:
	@echo "building app"
	@cargo build
casoE:
	@echo echo "Corriendo el caso de prueba 1 con solo 1 cafe"
	@cargo run caso-de-prueba-empate.txt

casoP:
	@echo "Corriendo el caso de prueba 2 con varios cafes"
	@cargo run caso-de-prueba-ninguna-gana.txt

casoB:
	@echo "Corriendo el caso de prueba 3 con varios cafes solo leche y uno con agua "
	@cargo run caso_gana_blanca.txt

casoN:
	@echo "Corriendo el caso de prueba 3 con varios cafes solo leche y uno con agua "
	@cargo run caso_gana_negra.txt